# This is a basic workflow to help you get started with Actions
name: Verificación de duplicados

# Controls when the workflow will run
on:  
  pull_request
jobs:
  # This workflow contains a single job called "build"
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:              
      - name: Check for duplicate code
        uses: platisd/duplicate-code-detection-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "src/"

    

